// import type { Metadata } from "next";
import Head from 'next/head';
import Navbar from "../components/Navbar";
import HeroSection from "../components/HeroSection";
import AboutSection from "../components/AboutSection";
import ProjectsSection from '../components/ProjectSection';
import EmailSection from '../components/EmailSection';
import Footer from '../components/Footer';

// export const metadata: Metadata = {
//   title: "Portofolio | Cesar Rais Akhtar",
//   description: "Generated by create next app",
// };

export default function Home() {
  return (
    <>
    <Head>
        <title>Portofolio | Cesar Rais Akhtar</title>
        <meta name="description" content="Web Developer Portfolio Cesar Rais Akhtar" />
    </Head>
    <main className="flex min-h-screen flex-col bg-[#121212]">
      <Navbar />
      <div className="container mt-24 mx-auto px-12 py-4">
        <HeroSection />
        {/* <AchievementsSection /> */}
        <AboutSection />
        <ProjectsSection />
        <EmailSection />
      </div>
      <Footer />
    </main>
    </>
  );
}